### ISSUE TITLE
Context?

### ISSUE THREAD

**Issue by titoBouzout** [modderme123/reactively#20]
I'm wondering if there's any way to access some sort of context, for setting and getting values.

**Comment by milomg** [comment]
If all you need is an easy way to pass reactive variables around, you could create a global variable that stores a reactive signal and use that as a replacement for context. 

Reactively doesn't have a more powerful version of context that can change based on ownership (like Solid), because reactively doesn't have ownership. If you're looking for ownership, it is possible that Reactively is too small for your use case, and something like [solidjs/signals](https://github.com/solidjs/signals) would be a better fit.

**Comment by titoBouzout** [comment]
I see, thanks. My main use case is a Router, but context could be used for other things.
